services:
  cuartoymita:
    container_name: cuartoymita
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    environment:
      - NODE_ENV=production
    command: npm run start
