const menu = {
    cafes: [
      {
        id: 1,
        title: "Espresso Clásico",
        category: "cafés",
        description: "Un espresso intenso y aromático, preparado con granos seleccionados para un sabor fuerte y equilibrado.",
      },
      {
        id: 2,
        title: "Café Americano",
        category: "cafés",
        description: "Un espresso alargado con agua caliente, ofreciendo un café suave pero con cuerpo.",
      },
      {
        id: 3,
        title: "Capuchino",
        category: "cafés",
        description: "Café espresso con leche vaporizada y espuma cremosa, coronado con un toque de cacao.",
      },
      {
        id: 4,
        title: "Latte Macchiato",
        category: "cafés",
        description: "Leche vaporizada con un toque de espresso, creando una combinación suave y cremosa.",
      },
      {
        id: 5,
        title: "Mocha",
        category: "cafés",
        description: "Una mezcla deliciosa de espresso, chocolate y leche, con un toque de crema batida.",
      },
      {
        id: 6,
        title: "Flat White",
        category: "cafés",
        description: "Una versión más intensa del latte, con más espresso y menos espuma para un sabor más pronunciado.",
      },
      {
        id: 7,
        title: "Café Bombón",
        category: "cafés",
        description: "Un espresso con leche condensada, ofreciendo un sabor dulce y equilibrado.",
      },
      {
        id: 8,
        title: "Affogato",
        category: "cafés",
        description: "Una combinación irresistible de espresso caliente servido sobre una bola de helado de vainilla.",
      },
    ],
    infusiones: [
      {
        id: 1,
        title: "Té Verde Sencha",
        category: "infusiones",
        description: "Té verde japonés de hojas frescas con un sabor herbal y ligeramente dulce, rico en antioxidantes.",
      },
      {
        id: 2,
        title: "Manzanilla",
        category: "infusiones",
        description: "Infusión suave y relajante con notas florales, ideal para calmar el cuerpo y la mente.",
      },
      {
        id: 3,
        title: "Rooibos Vainilla",
        category: "infusiones",
        description: "Infusión sudafricana sin cafeína con un toque de vainilla, de sabor dulce y afrutado.",
      },
      {
        id: 4,
        title: "Té Chai",
        category: "infusiones",
        description: "Mezcla especiada de té negro con canela, cardamomo, jengibre y clavo, perfecta para un toque exótico.",
      },
      {
        id: 5,
        title: "Menta Poleo",
        category: "infusiones",
        description: "Refrescante infusión de menta y poleo, con propiedades digestivas y un aroma intenso.",
      },
      {
        id: 6,
        title: "Té Rojo Pu-erh",
        category: "infusiones",
        description: "Té fermentado con notas terrosas, conocido por sus propiedades digestivas y su sabor robusto.",
      },
      {
        id: 7,
        title: "Flor de Hibisco",
        category: "infusiones",
        description: "Infusión de color vibrante con un toque ácido y afrutado, rica en vitamina C y antioxidantes.",
      },
      {
        id: 8,
        title: "Lavanda y Melisa",
        category: "infusiones",
        description: "Infusión relajante con notas florales, ideal para reducir el estrés y promover el descanso.",
      },
    ],
    embutidos : [
        {
          id: 1,
          title: "Jamón Ibérico",
          category: "embutidos",
          description: "Jamón curado de cerdo ibérico, de sabor intenso y textura suave.",
        },
        {
          id: 2,
          title: "Chorizo Ibérico",
          category: "embutidos",
          description: "Chorizo curado con pimentón, ajo y especias, de sabor ahumado y ligeramente picante.",
        },
        {
          id: 3,
          title: "Salchichón Ibérico",
          category: "embutidos",
          description: "Salchichón elaborado con carne magra de cerdo ibérico, con un toque de pimienta negra.",
        },
        {
          id: 4,
          title: "Lomo Embuchado",
          category: "embutidos",
          description: "Lomo de cerdo curado con pimentón y ajo, de textura tierna y sabor intenso.",
        },
        {
          id: 5,
          title: "Morcilla de Burgos",
          category: "embutidos",
          description: "Embutido a base de arroz, cebolla y sangre de cerdo, con un sabor especiado y textura cremosa.",
        },
        {
          id: 6,
          title: "Fuet",
          category: "embutidos",
          description: "Embutido fino de cerdo con una curación suave y un sabor delicado.",
        },
        {
          id: 7,
          title: "Longaniza de Payés",
          category: "embutidos",
          description: "Longaniza curada con un toque de pimienta y especias mediterráneas.",
        },
        {
          id: 8,
          title: "Sobrasada Mallorquina",
          category: "embutidos",
          description: "Embutido untuoso de cerdo con pimentón, típico de Mallorca.",
        },
    ],
      quesos : [
        {
          id: 1,
          title: "Queso Manchego",
          category: "quesos",
          description: "Queso de oveja con denominación de origen, de sabor intenso y textura firme.",
        },
        {
          id: 2,
          title: "Queso Idiazábal",
          category: "quesos",
          description: "Queso de leche de oveja con un característico toque ahumado.",
        },
        {
          id: 3,
          title: "Queso Cabrales",
          category: "quesos",
          description: "Queso azul elaborado con leche de vaca y oveja, de sabor fuerte y cremoso.",
        },
        {
          id: 4,
          title: "Queso Mahón",
          category: "quesos",
          description: "Queso de vaca con una curación media, de sabor ligeramente ácido y textura firme.",
        },
        {
          id: 5,
          title: "Queso Tetilla",
          category: "quesos",
          description: "Queso gallego de vaca con una textura cremosa y un sabor suave y mantecoso.",
        },
        {
          id: 6,
          title: "Queso de Burgos",
          category: "quesos",
          description: "Queso fresco de vaca, ligero y suave, ideal para combinar con miel o membrillo.",
        },
        {
          id: 7,
          title: "Queso Roncal",
          category: "quesos",
          description: "Queso de oveja con una maduración prolongada, de sabor fuerte y textura compacta.",
        },
        {
          id: 8,
          title: "Queso Torta del Casar",
          category: "quesos",
          description: "Queso extremeño de oveja, de pasta blanda y sabor intenso.",
        },
    ],
};
  export default menu;