import Header from "@/components/layout/Header";
import "../styles/main.scss";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Cuarto y Mita",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Header />
        {children}
        <Footer /> 
      </body>
    </html>
  );
}
